language: node_js
os: linux
cache: yarn
node_js:
  - stable
after_success:
  - yarn add codecov
  - "./node_modules/.bin/iamtest -c lcovonly && ./node_modules/.bin/codecov"
deploy:
  provider: npm
  email: anton@mokr.org
  api_key:
    secure: YOuOa0pC5lVV+/lS4n9yIGGY09i5cMEW/o0Ws5SdSUvUVru7p86dYeBav46iEUV6PK+QbTpcPPoDY9EyNAEqXxkXCZBykO0b2s0ZPdpUHifyq20/MHU/KLLZvO7N7wXiU4WmgeOMvbp+h/eyDaZfRrE4qNJzHslKB1sGhuOibHq8EsdnKclK0BonwFl7+Jg47yZtGuwEt9z1D0D8fE39dgNFEcsZFvT9SaqAWC9Idr1sdcywTsbkN2oLbg7VsKqUOFMqZcdtQSOnHtXiY09rIdEPc5vtIW/PUpzIgzMT0XHiZBSKER8QcdjT1iItYza7239HmU7fxZExsvAPLRwtlH6Pddzeo+iPPOieVjmtgO8RJeBCn1u7B5yzkP2jNlS7CDAX/JdOG5N+xuCxxm6Y7tIMPT3+P5CIg4V6bBUl1fsgpkHZiBTuk3YB4gEqkgtFqWDa1h1veW18uFOf/k/U/wrP6IAkB8kzuM0vMe++ao6edjX8Am6UC7i3U/I5ynyx/7f/yxgo+OraD0bWWu0MVUNj0ITI6HYgeapax+qVWNvD20GkcfAvr7X1eMyNKrTvZJ9P1KBxqzg7Z74gg1Bg5M0Rq2fUfJ5eVn/ZJfb54gZ/7fHSp2r+baLx4asINQdX+8TeSue8OxM1E06dypJ8DSi5NKzCJIeoWJmTVpS7uCA=
  on:
    tags: true
    repo: amokrushin/am-nginx-vhost
